split("\n")|map(split(","))|
   map({"cveId": .[3],
    "packageName": .[1],
    "packageVersion": "",
    "severity": .[4],
    "cvssScore": .[2],
    "title": .[0],
    "description": "",
    "link": "",
    "AV": "",
    "AC": "",
    "C": "",
    "I": "",
    "A": "",
    "hasFix": "",
    "exploit": "",
    "publicExploits": "",
    "published": "",
    "updated": "",
    "type": "",
})
